// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALNM062DRUNnIvXhsxonjKZo2ktqatQxk',
    appId: '1:95498666845:android:1bf3c1845709fa5aaf5eb4',
    messagingSenderId: '95498666845',
    projectId: 'health-app-95729',
    storageBucket: 'health-app-95729.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDs3Xh-mLqKkjU-Bfsopo6gzJMYSNysubw',
    appId: '1:95498666845:ios:a262ab1e56b13658af5eb4',
    messagingSenderId: '95498666845',
    projectId: 'health-app-95729',
    storageBucket: 'health-app-95729.firebasestorage.app',
    iosClientId: '95498666845-j3r0g10q37mvs3iamgui6mlkm3ehf5vs.apps.googleusercontent.com',
    iosBundleId: 'com.healthapp.healthApp',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-_LUO_iKE--jKyhBLDmRoMHT8Zx_u3Jw',
    appId: '1:95498666845:web:969b57dcf531cd9baf5eb4',
    messagingSenderId: '95498666845',
    projectId: 'health-app-95729',
    authDomain: 'health-app-95729.firebaseapp.com',
    storageBucket: 'health-app-95729.firebasestorage.app',
    measurementId: 'G-2EQNKY8C7K',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-_LUO_iKE--jKyhBLDmRoMHT8Zx_u3Jw',
    appId: '1:95498666845:web:59e3a77c8602eb64af5eb4',
    messagingSenderId: '95498666845',
    projectId: 'health-app-95729',
    authDomain: 'health-app-95729.firebaseapp.com',
    storageBucket: 'health-app-95729.firebasestorage.app',
    measurementId: 'G-J4Y9ZRMKH1',
  );
}
